# fname= input("insert your first name please")
# mname= input("insert your middle name please")  
# lname= input("insert your last name please")  
# print(f"Hallo {fname} {mname} {lname} ")
x= input("please enter a number?\n")
print(x)
y= input("please enter a number?\n")
print(y)
print((int(x)+int(y)))